site_name: "Chess App"
nav:
  - Home: index.md
  - Project Setup: project_setup.md
  - Software Requirements: software_requirements.md
  - Modules:
    - chessapp:
      - ChessApp: chessapp.md
      - Configuration: configuration.md
      - Model: chessapp.model.md
      - View: chessapp.view.md
      - Controller: chessapp.controller.md
      - Sound: chessapp.sound.md
      - Util: chessapp.util.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.integrate
    - navigation.top
  palette:
    primary: blue
    accent: blue
    toggle:
      icon: menu
      name: Menu
plugins:
 - search
 - mkdocstrings